var myNum;
myNum = 1;
console.log('myNum -> ', myNum);
var myStr;
myStr = 'Welcome to types in TS';
console.log('myStr -> ', myStr);
var myBool;
myBool = true;
console.log('myBool -> ', myBool);
var myAnyType;
myAnyType = 'Support any data type';
console.log('myAnyType -> ', myAnyType);
var arrStr;
arrStr = ['Hello', 'World'];
console.log('arrStr -> ', arrStr);
var arrNum;
arrNum = [1, 2, 3];
console.log('arrNum -> ', arrNum);
